// <auto-generated />
using System;
using Client.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Client.Persistence.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    [Migration("20240108234939_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Client.Domain.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82941a0d-d4e7-4c43-88b0-f48897bdb94c"),
                            Address = "Rue de tunis km 0.5 cité jardin",
                            Cin = "11020305",
                            CreatedBy = "karim",
                            DateCreated = new DateTime(2024, 1, 8, 23, 49, 39, 169, DateTimeKind.Utc).AddTicks(2229),
                            DateModified = new DateTime(2024, 1, 8, 23, 49, 39, 169, DateTimeKind.Utc).AddTicks(2231),
                            LastName = "Ben Zina",
                            ModifiedBy = "emna",
                            Name = "Emna",
                            PhoneNumber = "25756063"
                        },
                        new
                        {
                            Id = new Guid("b21d744a-c328-86d7-d45f-d3a483cf1bca"),
                            Address = "P.O. Box 262, 1469 Hendrerit Road",
                            Cin = "24122383",
                            CreatedBy = "karim",
                            DateCreated = new DateTime(2024, 1, 8, 23, 49, 39, 169, DateTimeKind.Utc).AddTicks(2248),
                            DateModified = new DateTime(2024, 1, 8, 23, 49, 39, 169, DateTimeKind.Utc).AddTicks(2249),
                            LastName = "Rowland",
                            ModifiedBy = "emna",
                            Name = "Raven",
                            PhoneNumber = "37724065"
                        },
                        new
                        {
                            Id = new Guid("9273f710-21d6-0cba-42b8-7a22a3338ca9"),
                            Address = "157-1645 Dictum. St.",
                            Cin = "12248084",
                            CreatedBy = "karim",
                            DateCreated = new DateTime(2024, 1, 8, 23, 49, 39, 169, DateTimeKind.Utc).AddTicks(2251),
                            DateModified = new DateTime(2024, 1, 8, 23, 49, 39, 169, DateTimeKind.Utc).AddTicks(2251),
                            LastName = "Boone",
                            ModifiedBy = "emna",
                            Name = "Imelda",
                            PhoneNumber = "31728272"
                        },
                        new
                        {
                            Id = new Guid("55122af3-bb25-a27c-5751-bacec0a31e67"),
                            Address = "Ap #566-3797 Non Rd.",
                            Cin = "77643679",
                            CreatedBy = "karim",
                            DateCreated = new DateTime(2024, 1, 8, 23, 49, 39, 169, DateTimeKind.Utc).AddTicks(2253),
                            DateModified = new DateTime(2024, 1, 8, 23, 49, 39, 169, DateTimeKind.Utc).AddTicks(2254),
                            LastName = "Brennan",
                            ModifiedBy = "emna",
                            Name = "Zane",
                            PhoneNumber = "28362418"
                        },
                        new
                        {
                            Id = new Guid("b383ee1f-9073-e756-c759-894f9bef1d39"),
                            Address = "Ap #467-720 Cursus Road",
                            Cin = "87646134",
                            CreatedBy = "karim",
                            DateCreated = new DateTime(2024, 1, 8, 23, 49, 39, 169, DateTimeKind.Utc).AddTicks(2256),
                            DateModified = new DateTime(2024, 1, 8, 23, 49, 39, 169, DateTimeKind.Utc).AddTicks(2257),
                            LastName = "Sullivan",
                            ModifiedBy = "emna",
                            Name = "Malcolm",
                            PhoneNumber = "98258532"
                        },
                        new
                        {
                            Id = new Guid("377a02b7-4b2e-3b69-ac46-530e8054a026"),
                            Address = "262-3388 A, Road",
                            Cin = "32714860",
                            CreatedBy = "karim",
                            DateCreated = new DateTime(2024, 1, 8, 23, 49, 39, 169, DateTimeKind.Utc).AddTicks(2261),
                            DateModified = new DateTime(2024, 1, 8, 23, 49, 39, 169, DateTimeKind.Utc).AddTicks(2262),
                            LastName = "West",
                            ModifiedBy = "emna",
                            Name = "Quinlan",
                            PhoneNumber = "14563616"
                        },
                        new
                        {
                            Id = new Guid("a21d744a-c328-86d7-d45f-d3a483cf1bca"),
                            Address = "123 Main Street",
                            Cin = "78901234",
                            CreatedBy = "karim",
                            DateCreated = new DateTime(2024, 1, 8, 23, 49, 39, 169, DateTimeKind.Utc).AddTicks(2265),
                            DateModified = new DateTime(2024, 1, 8, 23, 49, 39, 169, DateTimeKind.Utc).AddTicks(2266),
                            LastName = "Crawford",
                            ModifiedBy = "emna",
                            Name = "Lucas",
                            PhoneNumber = "45678901"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
